[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"

# 配置Edge Functions
[[edge_functions]]
  path = "/api/frame"
  function = "frame"

[[edge_functions]]
  path = "/.netlify/functions/narratives"
  function = "narratives"

# 为.well-known路径添加专门处理
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# 处理API路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 函数配置
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["faunadb"]

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 