[build]
  command = "echo '跳过构建，使用静态文件'"
  publish = "public"
  edge_functions = "netlify/edge-functions"
  [build.environment]
  FAUNA_SECRET_KEY = ""
  NEXT_PUBLIC_MONAD_RPC_URL = ""
  NEXT_PUBLIC_URL = ""

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"
  functions = "netlify/functions"

# 函数配置
[functions]
  external_node_modules = ["faunadb", "fauna"]
  node_bundler = "esbuild"

# Frame API路由
[[redirects]]
  from = "/api/frame"
  to = "/.netlify/functions/frame"
  status = 200
  force = true

# Well-known endpoints
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

# Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Frame API响应头
[[headers]]
  for = "/api/frame"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Type = "application/json"
    Access-Control-Allow-Credentials = "true"
    Cache-Control = "no-store, no-cache"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Frame图片缓存
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 