[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"

# Edge Functions配置
[[edge_functions]]
  function = "frame"
  path = "/api/frame-edge"

# 修改Frame接口重定向，优先使用Netlify函数
[[redirects]]
  from = "/api/frame"
  to = "/.netlify/functions/frame"
  status = 200
  force = true

# 为.well-known路径添加专门处理
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# 处理API路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 函数配置
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["faunadb", "fauna"]

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/frame"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 