[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"

# 使用边缘函数来处理Frame请求
[[edge_functions]]
  function = "frame"
  path = "/api/frame"

# 为.well-known路径添加专门处理
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# 使用Edge Function处理Frame请求
[[redirects]]
  from = "/api/frame"
  to = "/.netlify/edge-functions/frame"
  status = 200
  force = true

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 