[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"

# 为.well-known路径添加专门处理
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# Frame API路由处理
[[redirects]]
  from = "/api/frame"
  to = "/.netlify/functions/api/frame"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["faunadb"] 