[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"

# 简化的Edge Functions配置
[[edge_functions]]
  path = "/api/frame"
  function = "frame"

# 为.well-known路径添加专门处理
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# 使用原始Frame端点（不使用重定向）
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 