[build]
  command = "npm run build"
  functions = "netlify/functions"
  [build.environment]
  FAUNA_SECRET_KEY = ""
  NEXT_PUBLIC_MONAD_RPC_URL = ""
  NEXT_PUBLIC_URL = "https://castchain-narratives.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  functions = "netlify/functions"

# 函数配置
[functions]
  external_node_modules = ["faunadb", "fauna"]
  node_bundler = "esbuild"

# Well-known endpoints
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

# Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true





# API 响应头
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Type = "application/json"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 图片资源缓存
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"