[build]
  command = "npm run build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/api/narratives/:id/follow"
  to = "/.netlify/functions/narrative-follow/:id"
  status = 200

[[redirects]]
  from = "/api/narratives/:id/contributions"
  to = "/.netlify/functions/narrative-contributions/:id"
  status = 200

[[redirects]]
  from = "/api/narratives/:id/branches"
  to = "/.netlify/functions/narrative-branches/:id"
  status = 200

[[redirects]]
  from = "/api/narratives/:id"
  to = "/.netlify/functions/narrative-by-id/:id"
  status = 200

[[redirects]]
  from = "/api/branches/create"
  to = "/.netlify/functions/branch-create"
  status = 200

[[redirects]]
  from = "/api/contributions/:narrativeId/:contributionId/like"
  to = "/.netlify/functions/contribution-like/:narrativeId/:contributionId"
  status = 200

[[redirects]]
  from = "/api/notifications/:id/read"
  to = "/.netlify/functions/notification-read/:id"
  status = 200

[[redirects]]
  from = "/api/users/:id/achievements"
  to = "/.netlify/functions/user-achievements/:id"
  status = 200

[[redirects]]
  from = "/api/users/:id/notifications/read-all"
  to = "/.netlify/functions/user-notifications/:id"
  status = 200

[[redirects]]
  from = "/api/users/:id/notifications"
  to = "/.netlify/functions/user-notifications/:id"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
